# Generated by Django 5.1.1 on 2024-12-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0003_category_podcast_image_podcast_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episode",
            name="duration",
        ),
    ]
