# Generated by Django 5.1.1 on 2024-12-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0004_remove_episode_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="podcast",
            name="author",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
