# Generated by Django 5.1.1 on 2024-12-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0006_alter_podcast_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="author",
            field=models.CharField(max_length=255),
        ),
    ]
