# Generated by Django 5.1.1 on 2024-12-12 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0008_episode_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="podcast",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="episodes",
                to="podcasts.podcast",
            ),
        ),
    ]
