# Generated by Django 5.1.1 on 2024-12-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0009_alter_episode_podcast"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="ai_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
