# Generated by Django 5.1.1 on 2024-12-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_generation", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AIPodcast",
        ),
    ]
